### ISSUE TITLE
Maybe add a few general stores for food/water/equipment/clothing ?

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#11]
the gunstores are a bit packed with all these items in one store :)
might ass-well add the general stores back (without the radar)

or think of a twist on them

**Comment by JoSchaap** [comment]
need some player input on this since we just alterred the gunstore

**Comment by ZoneTrooper** [comment]
Yeah put in like 2 generall stores or 3,because right now the entire Island is overloadet with Food,Water,Money packs.Also they dont respawn,and in some cases a simple water bottle or can of food could destroy your vehicle when you drive over it.Allready had it multiple times,driving on the mainroud,and a can of food destroyed my tire and the engine block.Also it would be nice to reduce the normal objects that you can take with you,like barricades or stuff like that,because they are totally random placed and player placing them right on the roud after 2 hours all rouds are blocked with shit that destroy your vehicle in no time if you hit it with even 5 kmh.

**Comment by JoSchaap** [comment]
implemented in v2.3
https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/tree/%23TEMP_TESTING_V23
