### ISSUE TITLE
implement new version of antihax

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#13]
new version was posted on bis forums, have a look at it :)

**Comment by k4n30** [comment]
link?

**Comment by JoSchaap** [comment]
http://forums.bistudio.com/showthread.php?155354-ARMA-3-INSLimitedAdmin-Anti-Hacking-Script

**Comment by AgentRev** [comment]
I checked the code, and aside from the anti-teleport, which checks if a player has moved more than 200m within each second, and banned vehicles, it's the roughly the same thing as mine.

My latest update of the anti-hack in revision D is now anti-anti-hack-proof, if you still want it. It uses BIS_fnc_MP for communication, and the server-side flagging method is compileFinal'd. Everything now has checksums to make it harder for hackers to trigger flags for other players on purpose.

Anyway, anti-teleport is not a good thing, because it would also kick admins that teleport via Wasteland's U menu, and with banned vehicles, any hacker can just spawn a banned vehicle and give it to an unknowing victim, which would get <i>her</i> flagged, and not the hacker.

The funny thing is, most server owners seem to install that anti-hack right away in its current form, however the banned scripts and banned variables lists come empty, so in reality it isn't that much effective if you don't know where to find the values to detect. The only thing that comes with values is the banned addons list, but many hackers just use CheatEngine to detour the game to their scripts, so they don't need to use addons.

**Comment by JoSchaap** [comment]
oh you tackled them resetting the flags? i just kept renaming the eventhandler and variablenames every update :P

**Comment by AgentRev** [comment]
Yeah. Also, I separated everything in different files, but I made a single-file version too, I'll give it to you this evening.

**Comment by JoSchaap** [comment]
great, im trying to build new dialog windows (never done it before but i think im getting there) :)

http://cloud-2.steampowered.com/ugc/595880712235925448/51131F2A1BFA9261397B75753E35C5A3A44AD287/

**Comment by k4n30** [comment]
@AgentRev how can I contact you, I have my own which we could combine into a super antihack :)

**Comment by JoSchaap** [comment]
_edit_ misread it 

that dialog was for the gunstores etc :)

**Comment by JoSchaap** [comment]
@AgentRev  after concideration your version was indeed the better choice.
will be implemented in v2.1 https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/commit/0a7e630e31c9c9775df4b9b25972202d0b42a835
