### ISSUE TITLE
make stores content like suits etc rely on players side (right suit for right side)

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#23]

**Comment by AgentRev** [comment]
I think it's less complicated to just list them all, rather than having to create a team filter for every single item. Plus, it gives people the choice to pick whatever color they want.

If you wanted to do this because it clutters the equipment list, just make a 4th list for clothing items like me.

**Comment by JoSchaap** [comment]
Its because of the underwear bug that happens if opfor wears blufor clothing ;)

**Comment by AgentRev** [comment]
Wait, does it happen with uniforms other than ghillie suits?

**Comment by JoSchaap** [comment]
if a uniform has an O_ in frong of it B_ and I_ and C_ cannot wear it :)
and the other ways arround

**Comment by dvize** [comment]
Implemented this for you in my fork.  Tested it, it works but i'm new at scripting for arma so take it if you want it.

**Comment by JoSchaap** [comment]
oh i just wanted to add switches for the bugged suits that really need to be right sided

ghilly
wetsuit
fatiques

The way you did it might work, but will clutter the config.sgf :)

but i need to get the 2 step weapon purchasing to work first (so you can also but the correct ammo when clicking a gun) :)
